-- CREATE / DROP TABLE and name rules
CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, active BOOLEAN);
CREATE TABLE Users (x INTEGER);
CREATE TABLE logs (msg TEXT, at INTEGER);
CREATE TABLE mdb_secret (a INTEGER);
CREATE TABLE dup (a INTEGER, A TEXT);
CREATE TABLE twopk (a INTEGER PRIMARY KEY, b INTEGER PRIMARY KEY);
SELECT * FROM logs;
DROP TABLE logs;
DROP TABLE logs;
SELECT * FROM LOGS;
CREATE TABLE logs (msg TEXT);
SELECT * FROM logs;
